name: Import Publications From BibTeX
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Academic CLI
        run: |
          python -m pip install --upgrade pip
          pip install academic

      - name: Convert BibTeX to Publication Pages
        run: |
          academic import --bibtex content/publications/publications.bib --publication-dir content/publications --overwrite

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add content/publications
          git commit -m "Imported publications from BibTeX" || echo "No changes to commit"
          git push
